a = 6;
b = 8;
N = 48;
Ns = 2^9;
f = N*100;
T = 1/f;
fc = 1000*f;
m = 0.5;
t0=0;
tf=5*T;
ts = (tf-t0)/(Ns-1);
t = t0:ts:tf;
y = a*cos(2*pi*f*t + b);
Ac = a/m;
yc = b*sin(2*pi*fc*t + b);
ydc = (1+y/Ac).*yc;
subplot(211);
plot(t,y);
title('Tin hieu goc');
subplot(212);
plot(t,ydc);
title('Tin hieu sau dieu che AM');